import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from '@react-pdf/renderer';
import { STATUS_LABEL } from '@/lib/reports/format';
import type { DashboardSummary } from '@/types/domain';

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: '#111827', fontFamily: 'Helvetica' },
  title: { fontSize: 22, fontWeight: 700, marginBottom: 6 },
  subtitle: { color: '#6B7280', marginBottom: 18 },
  metrics: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  metric: { border: '1px solid #E5E7EB', padding: 8, width: '24%' },
  label: { fontSize: 8, color: '#6B7280', marginBottom: 4 },
  value: { fontSize: 16, fontWeight: 700 },
  section: { marginTop: 14 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 6 },
  row: { flexDirection: 'row', borderBottom: '1px solid #E5E7EB', paddingVertical: 5 },
  col: { flex: 1 },
  small: { color: '#6B7280', fontSize: 8 },
});

export async function buildDashboardPdf(
  summary: DashboardSummary,
  year: number,
  generatedBy: string,
  generatedAt = new Date()
) {
  return renderToBuffer(
    <Document title={`Dashboard Summary ${year}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Dashboard Summary</Text>
        <Text style={styles.subtitle}>
          {year} · Generated by {generatedBy} on {generatedAt.toLocaleString()}
        </Text>

        <View style={styles.metrics}>
          <View style={styles.metric}>
            <Text style={styles.label}>Completion</Text>
            <Text style={styles.value}>{summary.completion_rate}%</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Overdue</Text>
            <Text style={styles.value}>{summary.overdue_count}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Due soon</Text>
            <Text style={styles.value}>{summary.due_next_7_days}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Entries</Text>
            <Text style={styles.value}>{summary.entries_total}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Status</Text>
          {summary.by_status.map((row) => (
            <View key={row.status} style={styles.row}>
              <Text style={styles.col}>{STATUS_LABEL[row.status]}</Text>
              <Text>{row.count}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Assignees</Text>
          {summary.by_assignee.map((row) => (
            <View key={row.user_id} style={styles.row}>
              <Text style={styles.col}>{row.name}</Text>
              <Text style={styles.col}>{row.completion_rate}% complete</Text>
              <Text>{row.overdue_count} overdue</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Needs Attention</Text>
          {[...summary.overdue_entries, ...summary.upcoming_entries].map((entry) => (
            <View key={entry.id} style={styles.row}>
              <View style={styles.col}>
                <Text>{entry.task_list?.name ?? 'Task entry'}</Text>
                <Text style={styles.small}>{entry.period_label}</Text>
              </View>
              <Text>Due {entry.due_date}</Text>
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
}
