import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from '@react-pdf/renderer';
import { STATUS_HEX, STATUS_LABEL, periodHeader } from '@/lib/reports/format';
import type { TrackerReportData } from '@/lib/api/tracker-report-data';
import type { TrackerRow } from '@/lib/tracker-view';

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 8, color: '#111827', fontFamily: 'Helvetica' },
  cover: { padding: 40, fontSize: 12, color: '#111827', fontFamily: 'Helvetica' },
  title: { fontSize: 24, marginBottom: 8, fontWeight: 700 },
  subtitle: { fontSize: 11, color: '#4B5563', marginBottom: 22 },
  metricRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  metric: { border: '1px solid #E5E7EB', padding: 10, width: '24%' },
  metricLabel: { fontSize: 8, color: '#6B7280', marginBottom: 4 },
  metricValue: { fontSize: 18, fontWeight: 700 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 8 },
  table: { borderTop: '1px solid #D1D5DB', borderLeft: '1px solid #D1D5DB' },
  row: { flexDirection: 'row' },
  cell: {
    borderRight: '1px solid #D1D5DB',
    borderBottom: '1px solid #D1D5DB',
    padding: 4,
    minHeight: 20,
  },
  header: { backgroundColor: '#111827', color: '#FFFFFF', fontWeight: 700 },
  taskCell: { width: 118 },
  periodCell: { width: 48, textAlign: 'center' },
  muted: { color: '#6B7280' },
  footer: {
    position: 'absolute',
    bottom: 16,
    left: 28,
    right: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    color: '#6B7280',
    fontSize: 7,
  },
});

export async function buildTrackerPdf(
  data: TrackerReportData,
  generatedBy: string,
  generatedAt = new Date()
) {
  const frequency = data.site_tracker.tracker_category.frequency;
  const landscape = data.columns.length > 12;
  const rowsBySection = new Map<string, TrackerRow[]>();
  for (const row of data.rows) {
    const key = row.section?.id ?? 'ungrouped';
    if (!rowsBySection.has(key)) rowsBySection.set(key, []);
    rowsBySection.get(key)!.push(row);
  }

  const groups = data.sections.map((section) => ({
    name: section.name,
    rows: rowsBySection.get(section.id) ?? [],
  }));
  const ungroupedRows = rowsBySection.get('ungrouped') ?? [];
  if (ungroupedRows.length || groups.length === 0) {
    groups.push({ name: 'Ungrouped', rows: ungroupedRows });
  }

  return renderToBuffer(
    <Document title={`${data.site_tracker.tracker_category.name} ${data.site_tracker.year}`}>
      <Page size="A4" style={styles.cover}>
        <Text style={styles.title}>{data.site_tracker.tracker_category.name}</Text>
        <Text style={styles.subtitle}>
          {data.site_tracker.site.name} · {frequency} · {data.site_tracker.year}
        </Text>
        <View style={styles.metricRow}>
          <View style={styles.metric}>
            <Text style={styles.metricLabel}>Completion</Text>
            <Text style={styles.metricValue}>{data.summary.completion_rate}%</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.metricLabel}>Overdue</Text>
            <Text style={styles.metricValue}>{data.summary.overdue}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.metricLabel}>Done</Text>
            <Text style={styles.metricValue}>{data.summary.done + data.summary.done_late}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.metricLabel}>Entries</Text>
            <Text style={styles.metricValue}>{data.summary.total}</Text>
          </View>
        </View>
        <Text style={[styles.subtitle, { marginTop: 24 }]}>
          Generated by {generatedBy} on {generatedAt.toLocaleString()}
        </Text>
      </Page>

      {groups.map((group) => (
        <Page
          key={group.name}
          size="A4"
          orientation={landscape ? 'landscape' : 'portrait'}
          style={styles.page}
        >
          <Text style={styles.sectionTitle}>{group.name}</Text>
          <View style={styles.table}>
            <View style={styles.row} fixed>
              <Text style={[styles.cell, styles.header, styles.taskCell]}>Task item</Text>
              {data.columns.map((column) => (
                <Text key={column.key} style={[styles.cell, styles.header, styles.periodCell]}>
                  {periodHeader(column, frequency)}
                </Text>
              ))}
            </View>
            {group.rows.map((row) => (
              <View key={row.id} style={styles.row} wrap={false}>
                <View style={[styles.cell, styles.taskCell]}>
                  <Text>{row.taskList.name}</Text>
                  <Text style={styles.muted}>
                    {row.taskList.assignee?.name ?? row.taskList.assignee?.email ?? 'Unassigned'}
                  </Text>
                </View>
                {data.columns.map((column) => {
                  const entry = row.entriesByColumn.get(column.key);
                  return (
                    <Text
                      key={`${row.id}:${column.key}`}
                      style={
                        entry
                          ? [
                              styles.cell,
                              styles.periodCell,
                              { backgroundColor: `#${STATUS_HEX[entry.status]}` },
                            ]
                          : [styles.cell, styles.periodCell]
                      }
                    >
                      {entry ? STATUS_LABEL[entry.status] : ''}
                    </Text>
                  );
                })}
              </View>
            ))}
          </View>
          <View style={styles.footer} fixed>
            <Text>Generated by {generatedBy}</Text>
            <Text>{generatedAt.toLocaleString()}</Text>
          </View>
        </Page>
      ))}
    </Document>
  );
}
