-- ============================================================================
-- Migration 010 — HAKDA Phase 4d: notifications
-- ============================================================================
-- In-app notifications are generated by the API / Edge Function layer. As with
-- the rest of the app, RLS blocks direct authenticated/anon access and the
-- service role is the only database writer/reader.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notifications (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id  UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  site_id          UUID REFERENCES sites(id) ON DELETE SET NULL,
  kind             TEXT NOT NULL CHECK (kind IN (
                     'overdue',
                     'upcoming',
                     'assigned',
                     'status_changed'
                   )),
  title            TEXT NOT NULL,
  body             TEXT,
  payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key       TEXT NOT NULL UNIQUE,
  read_at          TIMESTAMPTZ,
  emailed_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
  ON notifications(user_id, read_at)
  WHERE read_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_user_recent
  ON notifications(user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_org_recent
  ON notifications(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_site_recent
  ON notifications(site_id, created_at DESC)
  WHERE site_id IS NOT NULL;

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_service_role_only" ON notifications;
CREATE POLICY "notifications_service_role_only"
  ON notifications FOR ALL
  TO authenticated, anon
  USING (false) WITH CHECK (false);

-- Optional cron setup, once the project has pg_cron + pg_net enabled and Vault
-- secrets named `project_url` and `publishable_key`:
--
-- SELECT cron.schedule(
--   'tracker-notifications-daily',
--   '0 22 * * *',
--   $$
--   SELECT net.http_post(
--     url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url')
--       || '/functions/v1/notification-scan',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer ' ||
--         (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'publishable_key')
--     ),
--     body := jsonb_build_object('source', 'pg_cron')
--   );
--   $$
-- );

-- ============================================================================
-- End of Migration 010
-- ============================================================================
